# https://github.com/actions/starter-workflows/blob/5104ac42744c84c675b2f9e1168e89f1dd60c059/ci/node.js.yml

name: Node.js CI

# https://help.github.com/en/actions/reference/workflow-syntax-for-github-actions#on
on: push

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, 16.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{matrix.node-version}}
        uses: actions/setup-node@v2
        with:
          node-version: ${{matrix.node-version}}
          cache: 'npm'
      - run: npm ci
      - run: npx playwright install --with-deps
      - run: npm run lint
      - run: npm run build
      - run: npm run npm:install:examples
      - run: npm run build:examples
      - run: npm run start:examples
      - run: npm run test:node-fetch
      - run: npm run test:e2e
      - run: npm run test:coverage:whatwg-fetch
      - run: npm run test:coverage:examples

      - name: Upload coverage to Code Climate
        run: |
          curl --location https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > cc-test-reporter
          chmod +x cc-test-reporter
          ./cc-test-reporter format-coverage --input-type clover --output coverage.fetch.json coverage/clover.xml
          ./cc-test-reporter format-coverage --input-type clover --output coverage.node-example.json examples/node/coverage/clover.xml
          ./cc-test-reporter format-coverage --input-type clover --output coverage.web-example.json examples/web/coverage/clover.xml
          ./cc-test-reporter sum-coverage --output coverage.total.json --parts 3 coverage.*.json
          ./cc-test-reporter upload-coverage --input coverage.total.json
        env:
          CC_TEST_REPORTER_ID: ${{secrets.CC_TEST_REPORTER_ID}}

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v2
        with:
          # FIXME https://github.com/codecov/codecov-action/issues/600#issuecomment-1003567615
          #files: coverage/clover.xml,examples/node/coverage/clover.xml,examples/web/coverage/clover.xml
          directory: coverage/
          fail_ci_if_error: true
          verbose: true
