# https://github.com/actions/starter-workflows/blob/aa9d3bc6cc46ac11a53ca196e504d4f901a8de8d/ci/node.js.yml

name: Node.js CI

# https://help.github.com/en/actions/reference/workflow-syntax-for-github-actions#on
on: push

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, 16.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{matrix.node-version}}
        uses: actions/setup-node@v1
        with:
          node-version: ${{matrix.node-version}}
      - uses: microsoft/playwright-github-action@v1
      - run: npm ci
      - run: npm run lint
      - run: npm run build
      - run: npm run npm:install:examples
      - run: npm run build:examples
      - run: npm run start:examples
      - run: npm run test:node-fetch
      - run: npm run test:e2e
      - run: npm run test:coverage:whatwg-fetch
      - run: npm run test:coverage:examples
